### ISSUE TITLE
Invalid markdown produced due to spacing

### ISSUE THREAD

**Issue by aeharding** [rehypejs/rehype-remark#17] opened 2024-03-22 21:27 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

10

### Steps to reproduce

- Visit https://stackblitz.com/edit/github-ukkrta-zn5bou?file=src%2Findex.ts
- Observe `<strong>Test: </strong>The test` is transformed to `**Test: **The test`

This was originally observed in the wild while copying text from nytimes.com

### Expected behavior

Valid markdown output.

### Actual behavior

Invalid markdown output.

**Comment by ChristianMurphy** [comment] 2024-03-22 21:52
Welcome @aeharding! 👋 
Sorry you ran into a spot of trouble.
This is a duplicate of https://github.com/syntax-tree/hast-util-to-mdast/issues/82 and https://github.com/orgs/syntax-tree/discussions/60#discussioncomment-2111096 are themselves duplicates of https://github.com/syntax-tree/mdast-util-to-markdown/issues/12
You can track the progress and add to the conversation there.

**Closed by ChristianMurphy** 2024-03-22 21:52 UTC
Labels: 🤞 phase/open

**Comment by ChristianMurphy** [comment] 2024-03-22 21:53
Duplicate of https://github.com/syntax-tree/mdast-util-to-markdown/issues/12
